#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    compartment = 1.0
    S2 = 0.0 / compartment
    k1 = 1.0
    S1 = 0.15 / compartment
    reaction1 = compartment * k1 * S1
    k1_proc = 0.5
    
    # save results

    return (
        [
            S1 * compartment,
            S2 * compartment,
            k1,
        ],
        
        [
            compartment,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,) = p.static
    (S1_,S2_,k1_,) = u 

    # Heta rules
    S2 = S2_ / compartment
    k1 = k1_
    S1 = S1_ / compartment
    reaction1 = compartment * k1 * S1
    k1_proc = 0.5
    
    #p.static .= [compartment,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1,  # dS2_/dt
      k1_proc,  # dk1_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,) = integrator.p.static
        (S1_,S2_,k1_,) = u

        # Heta rules
        S2 = S2_ / compartment
        k1 = k1_
        S1 = S1_ / compartment
        reaction1 = compartment * k1 * S1
        k1_proc = 0.5
        
        # calculate amounts
        compartment_ = compartment
        reaction1_ = reaction1
        k1_proc_ = k1_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00033 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00033 = x00033
)
tasks = ()

export models, tasks

end
