#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    compartment = 1.0
    S2 = 1e-6 / compartment
    k1 = 1.5
    S1 = 1.5e-6 / compartment
    reaction1 = compartment * k1 * S1
    
    # save results

    return (
        [
            S2 * compartment,
        ],
        
        [
            compartment,
            S1,
            k1,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,S1,k1,) = p.static
    (S2_,) = u 

    # Heta rules
    S2 = S2_ / compartment
    reaction1 = compartment * k1 * S1
    
    #p.static .= [compartment,S1,k1,]
    du .= [
      reaction1,  # dS2_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,S1,k1,) = integrator.p.static
        (S2_,) = u

        # Heta rules
        S2 = S2_ / compartment
        reaction1 = compartment * k1 * S1
        
        # calculate amounts
        compartment_ = compartment
        S1_ = S1 * compartment
        reaction1_ = reaction1
        k1_ = k1

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00226 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00226 = x00226
)
tasks = ()

export models, tasks

end
