#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  :k__reaction1_local,:k__reaction2_local,
)}(Float64[
  750000,0.3,
])

### initialization of ODE variables and Records
function start_(cons)
    #(k__reaction1_local,k__reaction2_local,) = cons

    # Heta initialize
    t = 0.0 # initial time
    C = 1.0
    S4 = 1e-7 / C
    S1 = 1.5e-6 / C
    S2 = 2e-6 / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = 1.5e-6 / C
    reaction2 = C * cons[2] * S3
    k = 0.25
    S4_proc = *(k, (1.0 / 250000.0))
    
    # save results

    return (
        [
            S1 * C,
            S2 * C,
            S3 * C,
            S4 * C,
        ],
        
        [
            C,
            k,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,k,) = p.static
    (S1_,S2_,S3_,S4_,) = u 

    # Heta rules
    S4 = S4_ / C
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = S3_ / C
    reaction2 = C * cons[2] * S3
    S4_proc = *(k, (1.0 / 250000.0))
    
    #p.static .= [C,k,]
    du .= [
      -reaction1+reaction2,  # dS1_/dt
      -reaction1+reaction2,  # dS2_/dt
      reaction1-reaction2,  # dS3_/dt
      S4_proc*C,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,k,) = integrator.p.static
        (S1_,S2_,S3_,S4_,) = u

        # Heta rules
        S4 = S4_ / C
        S1 = S1_ / C
        S2 = S2_ / C
        reaction1 = C * cons[1] * S1 * S2
        S3 = S3_ / C
        reaction2 = C * cons[2] * S3
        S4_proc = *(k, (1.0 / 250000.0))
        
        # calculate amounts
        C_ = C
        reaction1_ = reaction1
        reaction2_ = reaction2
        k_ = k
        S4_proc_ = S4_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00733 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00733 = x00733
)
tasks = ()

export models, tasks

end
