#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    k1 = 0.75
    compartment = 1.0
    S1 = 1.0 / compartment
    S2 = 1.0 / compartment
    reaction1 = compartment * k1 * S1 * S2
    k2 = 0.25
    compartment1 = 1.0
    S3 = 0.0 / compartment1
    reaction2 = compartment1 * k2 * (S2 + (-1.0) * S3)
    
    # save results

    return (
        [
            S1 * compartment,
            S2 * compartment,
            S3 * compartment1,
        ],
        
        [
            compartment,
            compartment1,
            k1,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,compartment1,k1,k2,) = p.static
    (S1_,S2_,S3_,) = u 

    # Heta rules
    S1 = S1_ / compartment
    S2 = S2_ / compartment
    reaction1 = compartment * k1 * S1 * S2
    S3 = S3_ / compartment1
    reaction2 = compartment1 * k2 * (S2 + (-1.0) * S3)
    
    #p.static .= [compartment,compartment1,k1,k2,]
    du .= [
      -reaction1,  # dS1_/dt
      2*reaction1-reaction1-reaction2,  # dS2_/dt
      reaction2,  # dS3_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,compartment1,k1,k2,) = integrator.p.static
        (S1_,S2_,S3_,) = u

        # Heta rules
        S1 = S1_ / compartment
        S2 = S2_ / compartment
        reaction1 = compartment * k1 * S1 * S2
        S3 = S3_ / compartment1
        reaction2 = compartment1 * k2 * (S2 + (-1.0) * S3)
        
        # calculate amounts
        compartment_ = compartment
        compartment1_ = compartment1
        reaction1_ = reaction1
        reaction2_ = reaction2
        k1_ = k1
        k2_ = k2

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00054 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00054 = x00054
)
tasks = ()

export models, tasks

end
