#= 
    This code was generated by heta-compiler of v0.5.9
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  :k1__reaction1_local,
)}(Float64[
  0.8,
])

### initialization of ODE variables and Records
function start_(cons)
    #(k1__reaction1_local,) = cons

    # Heta initialize
    t = 0.0 # initial time
    C = 1.0
    S2 = 2.0 / C
    S3 = 1.5 / C
    S4 = 4.0 / C
    S1 = 1.5 / C
    reaction1 = C * cons[1] * S1
    k1 = 0.75
    S3_proc = 0.5 * k1
    k2 = 0.25
    S4_proc = (-0.5) * k2
    
    # save results

    return (
        [
            S1 * C,
            S2 * C,
            S3 * C,
            S4 * C,
        ],
        
        [
            C,
            k1,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,k1,k2,) = p.static
    (S1_,S2_,S3_,S4_,) = u 

    # Heta rules
    S2 = S2_ / C
    S3 = S3_ / C
    S4 = S4_ / C
    S1 = S1_ / C
    reaction1 = C * cons[1] * S1
    S3_proc = 0.5 * k1
    S4_proc = (-0.5) * k2
    
    #p.static .= [C,k1,k2,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1,  # dS2_/dt
      S3_proc*C,  # dS3_/dt
      S4_proc*C,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,k1,k2,) = integrator.p.static
        (S1_,S2_,S3_,S4_,) = u

        # Heta rules
        S2 = S2_ / C
        S3 = S3_ / C
        S4 = S4_ / C
        S1 = S1_ / C
        reaction1 = C * cons[1] * S1
        S3_proc = 0.5 * k1
        S4_proc = (-0.5) * k2
        
        # calculate amounts
        C_ = C
        reaction1_ = reaction1
        k1_ = k1
        k2_ = k2
        S3_proc_ = S3_proc
        S4_proc_ = S4_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### time events

### discrete events
function event1_trigger_(u, t, integrator)
    cons = integrator.p.constants
    (C,k1,k2,) = integrator.p.static
    (S1_,S2_,S3_,S4_,) = u

    # Heta rules
    S2 = S2_ / C
    S3 = S3_ / C
    S4 = S4_ / C
    S1 = S1_ / C
    reaction1 = C * cons[1] * S1
    S3_proc = 0.5 * k1
    S4_proc = (-0.5) * k2
    

    return S1 < 0.5 ? 1 : -1
end

### continous events

### event assignments
function event1_assignment_(integrator)
    cons = integrator.p.constants
    t = integrator.t
    (C,k1,k2,) = integrator.p.static
    (S1_,S2_,S3_,S4_,) = integrator.u

    # Heta rules
    S2 = S2_ / C
    S3 = S3_ / C
    S4 = S4_ / C
    S1 = S1_ / C
    reaction1 = C * cons[1] * S1
    S3_proc = 0.5 * k1
    S4_proc = (-0.5) * k2
    
    # recalculated values
    (S2,) = (2.0,)
    
    # save results

    integrator.u .= [
        S1 * C,
        S2 * C,
        S3 * C,
        S4 * C,
    ]
    
    integrator.p.static .= [C,k1,k2,]
end


### OUTPUT ###

x00736 = Model(
  start_,
  ode_,
  [
      DEvent(event1_trigger_, event1_assignment_),
  ],
  make_saving_,
  constants_
)

models = (
    x00736 = x00736
)
tasks = ()

export models, tasks

end
