#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    k1 = 0.75
    C = 1.0
    S1 = 1.0 / C
    S2 = 2.0 / C
    reaction1 = C * k1 * S1 * S2
    k2 = 0.25
    S3 = 1.0 / C
    reaction2 = C * k2 * S3
    p1 = 0.1
    C_proc = (-1.0) * C * p1
    
    # save results

    return (
        [
            C,
            S1 * C,
            S2 * C,
            S3 * C,
        ],
        
        [
            k1,
            k2,
            p1,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (k1,k2,p1,) = p.static
    (C_,S1_,S2_,S3_,) = u 

    # Heta rules
    C = C_
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * k1 * S1 * S2
    S3 = S3_ / C
    reaction2 = C * k2 * S3
    C_proc = (-1.0) * C * p1
    
    #p.static .= [k1,k2,p1,]
    du .= [
      C_proc,  # dC_/dt
      -reaction1+reaction2,  # dS1_/dt
      -reaction1+reaction2,  # dS2_/dt
      reaction1-reaction2,  # dS3_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (k1,k2,p1,) = integrator.p.static
        (C_,S1_,S2_,S3_,) = u

        # Heta rules
        C = C_
        S1 = S1_ / C
        S2 = S2_ / C
        reaction1 = C * k1 * S1 * S2
        S3 = S3_ / C
        reaction2 = C * k2 * S3
        C_proc = (-1.0) * C * p1
        
        # calculate amounts
        reaction1_ = reaction1
        reaction2_ = reaction2
        k1_ = k1
        k2_ = k2
        p1_ = p1
        C_proc_ = C_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00052 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00052 = x00052
)
tasks = ()

export models, tasks

end
