#= 
    This code was generated by heta-compiler of v0.5.9
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    x = sin(10.0 * t)
    y = 2.958924275
    
    # save results

    return (
        [ 0.0 ], # init for fake variable
        [
            x,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (x,) = p.static
    () = u 

    # Heta rules
    y = 2.0 + delay(x, 0.5)
    
    #p.static .= [x,]
    du .= [ 1.0 ] # RHS for fake variable
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (x,) = integrator.p.static
        () = u

        # Heta rules
        y = 2.0 + delay(x, 0.5)
        
        # calculate amounts
        y_ = y
        x_ = x

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### time events

### discrete events

### continous events

### event assignments


### OUTPUT ###

x00941 = Model(
  start_,
  ode_,
  [
  ],
  make_saving_,
  constants_
)

models = (
    x00941 = x00941
)
tasks = ()

export models, tasks

end
