#= 
    This code was generated by heta-compiler of v0.5.9
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    C = 1.0
    A4 = 1.0 / C
    Kf1 = 1.0
    A2 = 3.0 / C
    Kr1 = 2.0
    reaction1 = C * (A4 * Kf1 + (-1.0) * A2 * Kr1)
    A1 = 2.0 / C
    Kf = 1.0
    A3 = 4.0 / C
    Kr = 2.0
    reaction2 = C * (A1 * A2 * Kf + (-1.0) * A3 * Kr)
    
    # save results

    return (
        [
            A1 * C,
            A3 * C,
            A4 * C,
        ],
        
        [
            C,
            A2,
            Kf1,
            Kr1,
            Kf,
            Kr,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,A2,Kf1,Kr1,Kf,Kr,) = p.static
    (A1_,A3_,A4_,) = u 

    # Heta rules
    A4 = A4_ / C
    reaction1 = C * (A4 * Kf1 + (-1.0) * A2 * Kr1)
    A1 = A1_ / C
    A3 = A3_ / C
    reaction2 = C * (A1 * A2 * Kf + (-1.0) * A3 * Kr)
    
    #p.static .= [C,A2,Kf1,Kr1,Kf,Kr,]
    du .= [
      -reaction2,  # dA1_/dt
      reaction2,  # dA3_/dt
      -reaction1,  # dA4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,A2,Kf1,Kr1,Kf,Kr,) = integrator.p.static
        (A1_,A3_,A4_,) = u

        # Heta rules
        A4 = A4_ / C
        reaction1 = C * (A4 * Kf1 + (-1.0) * A2 * Kr1)
        A1 = A1_ / C
        A3 = A3_ / C
        reaction2 = C * (A1 * A2 * Kf + (-1.0) * A3 * Kr)
        
        # calculate amounts
        C_ = C
        A2_ = A2 * C
        reaction1_ = reaction1
        reaction2_ = reaction2
        Kf1_ = Kf1
        Kr1_ = Kr1
        Kf_ = Kf
        Kr_ = Kr

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### time events

### discrete events

### continous events

### event assignments


### OUTPUT ###

x00873 = Model(
  start_,
  ode_,
  [
  ],
  make_saving_,
  constants_
)

models = (
    x00873 = x00873
)
tasks = ()

export models, tasks

end
