#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    compartment = 0.0
    k1 = 0.6
    S1 = 1.0
    S2 = 1.5
    reaction1 = k1 * S1 * S2
    k2 = 0.13
    S3 = 2.0
    S4 = 0.5
    reaction2 = k2 * S3 * S4
    
    # save results

    return (
        [
            S2,
            S4,
        ],
        
        [
            compartment,
            S1,
            S3,
            k1,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,S1,S3,k1,k2,) = p.static
    (S2_,S4_,) = u 

    # Heta rules
    S2 = S2_
    reaction1 = k1 * S1 * S2
    S4 = S4_
    reaction2 = k2 * S3 * S4
    
    #p.static .= [compartment,S1,S3,k1,k2,]
    du .= [
      -reaction1+reaction2,  # dS2_/dt
      reaction1-reaction2,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,S1,S3,k1,k2,) = integrator.p.static
        (S2_,S4_,) = u

        # Heta rules
        S2 = S2_
        reaction1 = k1 * S1 * S2
        S4 = S4_
        reaction2 = k2 * S3 * S4
        
        # calculate amounts
        compartment_ = compartment
        S1_ = S1
        S3_ = S3
        reaction1_ = reaction1
        reaction2_ = reaction2
        k1_ = k1
        k2_ = k2

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00246 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00246 = x00246
)
tasks = ()

export models, tasks

end
