#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  :k__reaction1_local,:k__reaction2_local,
)}(Float64[
  750,250,
])

### initialization of ODE variables and Records
function start_(cons)
    #(k__reaction1_local,k__reaction2_local,) = cons

    # Heta initialize
    t = 0.0 # initial time
    C = 1.0
    S1 = 0.001 / C
    S2 = 0.0012 / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = 0.002 / C
    S4 = 0.001 / C
    reaction2 = C * cons[2] * S3 * S4
    
    # save results

    return (
        [
            S1 * C,
            S2 * C,
            S3 * C,
            S4 * C,
        ],
        
        [
            C,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,) = p.static
    (S1_,S2_,S3_,S4_,) = u 

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = S3_ / C
    S4 = S4_ / C
    reaction2 = C * cons[2] * S3 * S4
    
    #p.static .= [C,]
    du .= [
      -reaction1+reaction2,  # dS1_/dt
      -reaction1+reaction2,  # dS2_/dt
      reaction1-reaction2,  # dS3_/dt
      reaction1-reaction2,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,) = integrator.p.static
        (S1_,S2_,S3_,S4_,) = u

        # Heta rules
        S1 = S1_ / C
        S2 = S2_ / C
        reaction1 = C * cons[1] * S1 * S2
        S3 = S3_ / C
        S4 = S4_ / C
        reaction2 = C * cons[2] * S3 * S4
        
        # calculate amounts
        C_ = C
        reaction1_ = reaction1
        reaction2_ = reaction2

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events
function event1_condition_(u, t, integrator)
    cons = integrator.p.constants
    (C,) = integrator.p.static
    (S1_,S2_,S3_,S4_,) = u

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = S3_ / C
    S4 = S4_ / C
    reaction2 = C * cons[2] * S3 * S4
    
    return S4 > S2 ? 1 : -1
end

function event1_assignment_(integrator)
    cons = integrator.p.constants
    t = integrator.t
    (C,) = integrator.p.static
    (S1_,S2_,S3_,S4_,) = integrator.u

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = S3_ / C
    S4 = S4_ / C
    reaction2 = C * cons[2] * S3 * S4
    
    # recalculated values
    (S1,) = ((1.0 / 500.0),)
    
    # save results

    integrator.u .= [
        S1 * C,
        S2 * C,
        S3 * C,
        S4 * C,
    ]
    
    integrator.p.static .= [C,]
end
function event2_condition_(u, t, integrator)
    cons = integrator.p.constants
    (C,) = integrator.p.static
    (S1_,S2_,S3_,S4_,) = u

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = S3_ / C
    S4 = S4_ / C
    reaction2 = C * cons[2] * S3 * S4
    
    return S3 > (9.0 / 4000.0) ? 1 : -1
end

function event2_assignment_(integrator)
    cons = integrator.p.constants
    t = integrator.t
    (C,) = integrator.p.static
    (S1_,S2_,S3_,S4_,) = integrator.u

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * cons[1] * S1 * S2
    S3 = S3_ / C
    S4 = S4_ / C
    reaction2 = C * cons[2] * S3 * S4
    
    # recalculated values
    (S4,) = ((1.0 / 1000.0),)
    
    # save results

    integrator.u .= [
        S1 * C,
        S2 * C,
        S3 * C,
        S4 * C,
    ]
    
    integrator.p.static .= [C,]
end


### OUTPUT ###

x00392 = Model(
  start_,
  ode_,
  [(event1_condition_, event1_assignment_), (event2_condition_, event2_assignment_), ],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00392 = x00392
)
tasks = ()

export models, tasks

end
