#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  :kf__reaction1_local,:kr__reaction1_local,:kf__reaction2_local,:kr__reaction2_local,
)}(Float64[
  0.8,0.06,0.9,0.075,
])

### initialization of ODE variables and Records
function start_(cons)
    #(kf__reaction1_local,kr__reaction1_local,kf__reaction2_local,kr__reaction2_local,) = cons

    # Heta initialize
    t = 0.0 # initial time
    C = 1.0
    S1 = 1.0 / C
    S2 = 0.0 / C
    reaction1 = C * (cons[1] * S1 + (-1.0) * cons[2] * S2)
    S3 = 1.5 / C
    S4 = 0.5 / C
    reaction2 = C * (cons[3] * S3 + (-1.0) * cons[4] * S4)
    
    # save results

    return (
        [
            S1 * C,
            S2 * C,
            S3 * C,
            S4 * C,
        ],
        
        [
            C,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,) = p.static
    (S1_,S2_,S3_,S4_,) = u 

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * (cons[1] * S1 + (-1.0) * cons[2] * S2)
    S3 = S3_ / C
    S4 = S4_ / C
    reaction2 = C * (cons[3] * S3 + (-1.0) * cons[4] * S4)
    
    #p.static .= [C,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1,  # dS2_/dt
      -reaction2,  # dS3_/dt
      reaction2,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,) = integrator.p.static
        (S1_,S2_,S3_,S4_,) = u

        # Heta rules
        S1 = S1_ / C
        S2 = S2_ / C
        reaction1 = C * (cons[1] * S1 + (-1.0) * cons[2] * S2)
        S3 = S3_ / C
        S4 = S4_ / C
        reaction2 = C * (cons[3] * S3 + (-1.0) * cons[4] * S4)
        
        # calculate amounts
        C_ = C
        reaction1_ = reaction1
        reaction2_ = reaction2

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00831 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00831 = x00831
)
tasks = ()

export models, tasks

end
