#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    k1 = 75.0
    C = 1.0
    S1 = 0.01 / C
    S2 = 0.012 / C
    reaction1 = C * k1 * S1 * S2
    k2 = 25.0
    S3 = 0.02 / C
    S4 = 0.01 / C
    reaction2 = C * k2 * S3 * S4
    
    # save results

    return (
        [
            S1 * C,
            S2 * C,
            S3 * C,
        ],
        
        [
            C,
            S4,
            k1,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,S4,k1,k2,) = p.static
    (S1_,S2_,S3_,) = u 

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * k1 * S1 * S2
    S3 = S3_ / C
    reaction2 = C * k2 * S3 * S4
    
    #p.static .= [C,S4,k1,k2,]
    du .= [
      -reaction1+reaction2,  # dS1_/dt
      -reaction1+reaction2,  # dS2_/dt
      reaction1-reaction2,  # dS3_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,S4,k1,k2,) = integrator.p.static
        (S1_,S2_,S3_,) = u

        # Heta rules
        S1 = S1_ / C
        S2 = S2_ / C
        reaction1 = C * k1 * S1 * S2
        S3 = S3_ / C
        reaction2 = C * k2 * S3 * S4
        
        # calculate amounts
        C_ = C
        S4_ = S4 * C
        reaction1_ = reaction1
        reaction2_ = reaction2
        k1_ = k1
        k2_ = k2

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events
function event1_condition_(u, t, integrator)
    cons = integrator.p.constants
    (C,S4,k1,k2,) = integrator.p.static
    (S1_,S2_,S3_,) = u

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * k1 * S1 * S2
    S3 = S3_ / C
    reaction2 = C * k2 * S3 * S4
    
    return S2 < S4 ? 1 : -1
end

function event1_assignment_(integrator)
    cons = integrator.p.constants
    t = integrator.t
    (C,S4,k1,k2,) = integrator.p.static
    (S1_,S2_,S3_,) = integrator.u

    # Heta rules
    S1 = S1_ / C
    S2 = S2_ / C
    reaction1 = C * k1 * S1 * S2
    S3 = S3_ / C
    reaction2 = C * k2 * S3 * S4
    
    # recalculated values
    (S1,S3,) = ((1.0 / 50.0),(1.0 / 200.0),)
    
    # save results

    integrator.u .= [
        S1 * C,
        S2 * C,
        S3 * C,
    ]
    
    integrator.p.static .= [C,S4,k1,k2,]
end


### OUTPUT ###

x00386 = Model(
  start_,
  ode_,
  [(event1_condition_, event1_assignment_), ],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00386 = x00386
)
tasks = ()

export models, tasks

end
