#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    p1 = 0.1
    p2 = 1.5
    compartment = 1.0
    S2 = 0.0 / compartment
    k1 = 0.9
    S1 = 1.5 / compartment
    reaction1 = compartment * k1 * S1
    p2_proc = 0.1
    
    # save results

    return (
        [
            S1 * compartment,
            S2 * compartment,
            p2,
        ],
        
        [
            k1,
            p1,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (k1,p1,) = p.static
    (S1_,S2_,p2_,) = u 

    # Heta rules
    p2 = p2_
    compartment = p1 * p2
    S2 = S2_ / compartment
    S1 = S1_ / compartment
    reaction1 = compartment * k1 * S1
    p2_proc = 0.1
    
    #p.static .= [k1,p1,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1,  # dS2_/dt
      p2_proc,  # dp2_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (k1,p1,) = integrator.p.static
        (S1_,S2_,p2_,) = u

        # Heta rules
        p2 = p2_
        compartment = p1 * p2
        S2 = S2_ / compartment
        S1 = S1_ / compartment
        reaction1 = compartment * k1 * S1
        p2_proc = 0.1
        
        # calculate amounts
        compartment_ = compartment
        reaction1_ = reaction1
        k1_ = k1
        p1_ = p1
        p2_proc_ = p2_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00311 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00311 = x00311
)
tasks = ()

export models, tasks

end
