#= 
    This code was generated by heta-compiler of v0.5.8
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    P = Inf
    Q = -Inf
    R = NaN
    
    # save results

    return (
        [ 0.0 ], # init for fake variable
        [
            P,
            Q,
            R,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (P,Q,R,) = p.static
    () = u 

    # Heta rules
    
    #p.static .= [P,Q,R,]
    du .= [ 1.0 ] # RHS for fake variable
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (P,Q,R,) = integrator.p.static
        () = u

        # Heta rules
        
        # calculate amounts
        P_ = P
        Q_ = Q
        R_ = R

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### time events

### discrete events


### continous events


### event assignments


### OUTPUT ###

x00950 = Model(
  start_,
  ode_,
  [
  ],
  make_saving_,
  constants_
)

models = (
    x00950 = x00950
)
tasks = ()

export models, tasks

end
