#= 
    This code was generated by heta-compiler of v0.5.8
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    k2 = 0.75
    P2 = 0.0
    P1_proc = ^(e, (-1.0) * t) * k2 * P2
    k1 = 1.0
    P1 = 1.5
    P2_proc = ^(e, (-1.0) * t) * k1 * P1
    
    # save results

    return (
        [
            P1,
            P2,
        ],
        
        [
            k1,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (k1,k2,) = p.static
    (P1_,P2_,) = u 

    # Heta rules
    P2 = P2_
    P1_proc = ^(e, (-1.0) * t) * k2 * P2
    P1 = P1_
    P2_proc = ^(e, (-1.0) * t) * k1 * P1
    
    #p.static .= [k1,k2,]
    du .= [
      P1_proc,  # dP1_/dt
      P2_proc,  # dP2_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (k1,k2,) = integrator.p.static
        (P1_,P2_,) = u

        # Heta rules
        P2 = P2_
        P1_proc = ^(e, (-1.0) * t) * k2 * P2
        P1 = P1_
        P2_proc = ^(e, (-1.0) * t) * k1 * P1
        
        # calculate amounts
        k1_ = k1
        k2_ = k2
        P1_proc_ = P1_proc
        P2_proc_ = P2_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### time events

### discrete events


### continous events


### event assignments


### OUTPUT ###

x00892 = Model(
  start_,
  ode_,
  [
  ],
  make_saving_,
  constants_
)

models = (
    x00892 = x00892
)
tasks = ()

export models, tasks

end
