#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    S2 = 0.0
    k1 = 1.0
    S1 = 0.15
    S1_proc = (-1.0) * k1 * S1
    S2_proc = k1 * S1
    
    # save results

    return (
        [
            S1,
            S2,
        ],
        
        [
            k1,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (k1,) = p.static
    (S1_,S2_,) = u 

    # Heta rules
    S2 = S2_
    S1 = S1_
    S1_proc = (-1.0) * k1 * S1
    S2_proc = k1 * S1
    
    #p.static .= [k1,]
    du .= [
      S1_proc,  # dS1_/dt
      S2_proc,  # dS2_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (k1,) = integrator.p.static
        (S1_,S2_,) = u

        # Heta rules
        S2 = S2_
        S1 = S1_
        S1_proc = (-1.0) * k1 * S1
        S2_proc = k1 * S1
        
        # calculate amounts
        k1_ = k1
        S1_proc_ = S1_proc
        S2_proc_ = S2_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00176 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00176 = x00176
)
tasks = ()

export models, tasks

end
