#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    compartment = 1.0
    S1 = 7.0
    
    # save results

    return (
        [ 0.0 ], # init for fake variable
        [
            compartment,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,) = p.static
    () = u 

    # Heta rules
    S1 = 7.0
    
    #p.static .= [compartment,]
    du .= [ 1.0 ] # RHS for fake variable
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,) = integrator.p.static
        () = u

        # Heta rules
        S1 = 7.0
        
        # calculate amounts
        compartment_ = compartment
        S1_ = S1 * compartment

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00030 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00030 = x00030
)
tasks = ()

export models, tasks

end
