#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    compartment = 1.0
    S3 = 10.0 / compartment
    S4 = 0.0 / compartment
    k1 = 1.0
    S1 = 10.0 / compartment
    reaction1 = compartment * k1 * S1
    S2 = 0.0 / compartment
    p1 = 1.5
    p2 = 0.05
    reaction2 = ((S2 > 4.0 && S1 < 5.0 && S2 < 8.0) ? p1 : p2)
    
    # save results

    return (
        [
            S1 * compartment,
            S2 * compartment,
            S3 * compartment,
            S4 * compartment,
        ],
        
        [
            compartment,
            p1,
            p2,
            k1,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,p1,p2,k1,) = p.static
    (S1_,S2_,S3_,S4_,) = u 

    # Heta rules
    S3 = S3_ / compartment
    S4 = S4_ / compartment
    S1 = S1_ / compartment
    reaction1 = compartment * k1 * S1
    S2 = S2_ / compartment
    reaction2 = ((S2 > 4.0 && S1 < 5.0 && S2 < 8.0) ? p1 : p2)
    
    #p.static .= [compartment,p1,p2,k1,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1,  # dS2_/dt
      -reaction2,  # dS3_/dt
      reaction2,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,p1,p2,k1,) = integrator.p.static
        (S1_,S2_,S3_,S4_,) = u

        # Heta rules
        S3 = S3_ / compartment
        S4 = S4_ / compartment
        S1 = S1_ / compartment
        reaction1 = compartment * k1 * S1
        S2 = S2_ / compartment
        reaction2 = ((S2 > 4.0 && S1 < 5.0 && S2 < 8.0) ? p1 : p2)
        
        # calculate amounts
        compartment_ = compartment
        reaction1_ = reaction1
        reaction2_ = reaction2
        p1_ = p1
        p2_ = p2
        k1_ = k1

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00198 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00198 = x00198
)
tasks = ()

export models, tasks

end
