#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  :k2__reaction1_local,:k2__reaction3_local,
)}(Float64[
  0.7,1,
])

### initialization of ODE variables and Records
function start_(cons)
    #(k2__reaction1_local,k2__reaction3_local,) = cons

    # Heta initialize
    t = 0.0 # initial time
    C = 1.0
    S4 = 0.0 / C
    S1 = 1e-4 / C
    reaction1 = C * cons[1] * S1 * t
    k2 = 0.5
    S2 = 0.0 / C
    reaction2 = C * k2 * S2 * t
    S3 = 0.0 / C
    reaction3 = C * cons[2] * S3 * t
    
    # save results

    return (
        [
            S1 * C,
            S2 * C,
            S3 * C,
            S4 * C,
        ],
        
        [
            C,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (C,k2,) = p.static
    (S1_,S2_,S3_,S4_,) = u 

    # Heta rules
    S4 = S4_ / C
    S1 = S1_ / C
    reaction1 = C * cons[1] * S1 * t
    S2 = S2_ / C
    reaction2 = C * k2 * S2 * t
    S3 = S3_ / C
    reaction3 = C * cons[2] * S3 * t
    
    #p.static .= [C,k2,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1-reaction2,  # dS2_/dt
      reaction2-reaction3,  # dS3_/dt
      reaction3,  # dS4_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (C,k2,) = integrator.p.static
        (S1_,S2_,S3_,S4_,) = u

        # Heta rules
        S4 = S4_ / C
        S1 = S1_ / C
        reaction1 = C * cons[1] * S1 * t
        S2 = S2_ / C
        reaction2 = C * k2 * S2 * t
        S3 = S3_ / C
        reaction3 = C * cons[2] * S3 * t
        
        # calculate amounts
        C_ = C
        reaction1_ = reaction1
        reaction2_ = reaction2
        reaction3_ = reaction3
        k2_ = k2

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00897 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00897 = x00897
)
tasks = ()

export models, tasks

end
