# This workflow build Heta platform and share results in "display" branch

name: Build and simulate

on:
  workflow_dispatch:
    inputs: {}
    #  name:
    #    description: 'Manual run of build and simulate'
    #    default: 'World'
    #    required: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 8.x ]
        heta-version: [ latest ]
        platform: [ ubuntu-latest ]

    runs-on: self-hosted # ${{ matrix.platform }}
    
    defaults:
          run:
            shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Heta-compiler installation
      run: |
        # npm i -g heta-compiler@${{ matrix.heta-version }}
        npm i -g https://github.com/insysbio/heta-compiler.git
    - run: |
        heta build
        heta_version=`heta -v`
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.1.12
      with:
        version: ~1.5.0 # optional, default is 1
        arch: x64 # optional, default is x64
        show-versioninfo: true # optional, default is false
    - name: SimSolver installation
      run: julia -e 'using Pkg;Pkg.activate(".");Pkg.add(url="https://${{ secrets.SIMSOLVER_GITLAB_TOKEN }}@gitlab.insysbio.com/dev-group/simsolver", rev="dev")'
    - name: Run Julia simulations
      run: julia ./run.jl $heta_version
    - name: Copy files to "static"
      run: |
        mkdir -p ./result/cases/output
        cp -rf ./cases/output/*.csv ./result/cases/output/ | true
        cp -rf ./cases/output/*.png ./result/cases/output/ | true
        cp -f ./build.log ./result/
        cp -f ./results.json ./result/
    - name: Deploy to "result" branch only for "master" and "*-result" pushes
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: result # The branch the action should deploy to.
        FOLDER: result # The folder the action should deploy.
    - name: Upload artefacts
      uses: actions/upload-artifact@v2
      with:
        name: sim-result
        path: |
          ./build.log
          ./results.json
          ./cases/output/*.csv
          ./cases/output/*.png
