name: convert to L2V5

on:
  workflow_dispatch: {}
  push:
    branches: [ master, '*-result' ]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installations of heta-compiler from repository
        run: |
          npm ci
          npm i hetalang/heta-compiler
          npx heta -v

      - name: Download semantic cases of version 3.4.0
        run: |
          mkdir -p cases
          curl -L -o cases/semantic_tests.zip https://github.com/sbmlteam/sbml-test-suite/releases/download/3.4.0/semantic_tests.v3.4.0.zip
          unzip cases/semantic_tests.zip -d cases/
          
      - name: Create file structure
        run: |
          bash ./bash/make-summary.sh

      - name: Create collection of heta files with comments as synopsis
        run: |
          BASE_DIR=./result/latest node ./js/convert-to-heta.js

      - name: copy static
        run: |
          cp -r static/* result/

      - name: Commit changes to result branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: result # The branch the action should deploy to.
          FOLDER: result # The folder the action should deploy.
          CLEAN: true
