#= 
    This code was generated by heta-compiler of v0.5.3
    
=#

module julia 
using SimSolver

### create default constants
constants_ = NamedTuple{(
  
)}(Float64[
  
])

### initialization of ODE variables and Records
function start_(cons)
    #() = cons

    # Heta initialize
    t = 0.0 # initial time
    compartment = 1.0
    S2 = 1e-4 / compartment
    S3 = 1e-4 / compartment
    k1 = 1.75
    S1 = 1.5e-4 / compartment
    reaction1 = compartment * k1 * S1
    k2 = 1.5e-5
    S3_proc = k1 * k2
    
    # save results

    return (
        [
            S1 * compartment,
            S2 * compartment,
            S3 * compartment,
        ],
        
        [
            compartment,
            k1,
            k2,
        ]
    )
end

### calculate RHS of ODE
function ode_(du, u, p, t)
    cons = p.constants
    (compartment,k1,k2,) = p.static
    (S1_,S2_,S3_,) = u 

    # Heta rules
    S2 = S2_ / compartment
    S3 = S3_ / compartment
    S1 = S1_ / compartment
    reaction1 = compartment * k1 * S1
    S3_proc = k1 * k2
    
    #p.static .= [compartment,k1,k2,]
    du .= [
      -reaction1,  # dS1_/dt
      reaction1,  # dS2_/dt
      S3_proc*compartment,  # dS3_/dt
    ]
end

### output function
function make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (compartment,k1,k2,) = integrator.p.static
        (S1_,S2_,S3_,) = u

        # Heta rules
        S2 = S2_ / compartment
        S3 = S3_ / compartment
        S1 = S1_ / compartment
        reaction1 = compartment * k1 * S1
        S3_proc = k1 * k2
        
        # calculate amounts
        compartment_ = compartment
        reaction1_ = reaction1
        k1_ = k1
        k2_ = k2
        S3_proc_ = S3_proc

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### events


### OUTPUT ###

x00334 = Model(
  start_,
  ode_,
  [],
  [], # place for discrete events, not used
  make_saving_,
  constants_
)

models = (
    x00334 = x00334
)
tasks = ()

export models, tasks

end
